### ISSUE TITLE
Crash on installing Netfix apkm on Note 4

### ISSUE THREAD

**Issue by TifaAA18** [android-police/apkmirror-public#121]
#### Expected behavior
Install should start and successfully finish

#### Actual behavior
apkmirror installer crashes

#### Steps to reproduce the problem
browse to apkm, tap install,  wait for progress bar to be full

Galaxy Note 4 SM-N910C, rooted
Netflix 7.48.0 build 10 34747 apkm

**Comment by archon810** [comment]
Hi, we just released version 1.1.2 - can you please retest with this version? 

Otherwise, I think it's something with older Samsung devices, same as https://github.com/android-police/apkmirror-public/issues/118.

**Comment by TifaAA18** [comment]
Just to add: the error "unable to list files inside apkm bundle" appears for a split second (had to video capture screen to read it, probably a logging feature could be useful), before the system gives app stopped message and crash back to home.

The issue still exists in this release. I tried it Netflix 7.49.0 build 19 34761 apkm too. I guess I'm out of luck with this trusty old device.

**Comment by archon810** [comment]
We should have a longer term solution soon, I suspect your device is missing libsodium encryption compatibility. In the shorter term, we should at least fix the crashes and maybe make the error more descriptive. Time to dig out my Note3 and run a test.

**Comment by archon810** [comment]
The Note 4, just like the Note 3, is missing the necessary method in the OS to install split APKs (or it's only made available to the Play Store), so unfortunately this cannot be fixed.
